# Generated by Django 2.2.27 on 2022-02-06 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='作品タイトル')),
                ('youtube_html', models.TextField(verbose_name='youtube動画')),
                ('use_language', models.TextField(verbose_name='使用言語')),
                ('discription', models.TextField(verbose_name='説明')),
                ('details', models.TextField(blank=True, null=True, verbose_name='URL')),
                ('github', models.CharField(blank=True, max_length=100, null=True, verbose_name='github')),
            ],
        ),
    ]
